PORTNAME=	zabbix-api
DISTVERSION=	0.5.4
CATEGORIES=	net-mgmt python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	y@trombik.org
COMMENT=	Python zabbix API

LICENSE=	LGPL21

USES=		python
USE_PYTHON=	distutils

.include <bsd.port.mk>
